# SPDX-License-Identifier: BSD-3-Clause
---
- hosts: network-test
  vars:
    network_connections:

      # Create a bond master
      - name: bond0
        state: up
        type: bond
        interface_name: bond0
        # bond configuration settings: (optional)
        bond:
          mode: active-backup
          miimon: 110

      # enslave an ethernet to the bond
      - name: slave1
        state: up
        type: ethernet
        interface_name: eth1
        master: bond0

      # enslave a second ethernet to the bond
      - name: slave2
        state: up
        type: ethernet
        interface_name: eth2
        master: bond0

  roles:
    - linux-system-roles.network
...
